#164489773] setup eslint
andela/strikers-ah-backend pull request #1
Opened 2019-03-19 10:02 UTC by Inclet

#### What does this PR do?
1. setup eslint : eslint, eslint-config-airbnb, eslint-plugin-import, eslint-plugin-jsx-a11y, eslint-plugin-react
#### Description of Task to be completed?
Have eslint in our project.
#### How should this be manually tested?
1. check `package.json` under `devdependencies`.
2. when cloning or pulling this branch do `npm install`
#### What are the relevant pivotal tracker stories?
Configure ESLint #164489773
[Pivotal Link](https://www.pivotaltracker.com/story/show/164489773)
#### Screenshots (if appropriate)
<img width="432" alt="Screen Shot 2019-03-19 at 12 00 41" src="https://user-images.githubusercontent.com/37753967/54597127-b06ef400-4a3e-11e9-9ffd-87bc42e4b04b.png">

2019-03-19 10:10 UTC, mwibutsa approved these changes
Thank you for installing Eslint

2019-03-19 10:14 UTC, mystere10 commented
1. Remove the bracket in the PR name

2019-03-19 10:22 UTC, frankhn requested changes
Thanks for your effort @Inclet, but few things to note here.
 1. Description of the PR on the task to be completed isn't meaningful please check it out and make it more descriptive.
 2. Test for Eslint(Airbnb) should be tested when someone does not follow the rules specified respectively, so having Eslint in our project doesn't prove that it's working. I'd say that it would be better to dive into that and specify at least one thing that proves that Eslint really working.
     Specify the tests you run to verify your changes. 
     https://github.com/andela/engineering-playbook/blob/master/assets/pr-sample.png

3. Please add the rules in .eslintrc.js file as specified in the story
![image](https://user-images.githubusercontent.com/33962360/54663357-aa821d00-4ae9-11e9-9784-573fa61b58ff.png)

2019-03-19 10:50 UTC, mystere10 reviewed
Thank for the work done,
You should have mentioned that you used airbnb as eslint configuration in the description

2019-03-19 12:07 UTC, Inclet commented
> Thanks for your effort @Inclet, but few things to note here.
> 
> 1. Naming the branch.
=> I named the branch `ch-configure-ESLINT-164489773` as you will see at the top of PR description.
> 2. Description of the PR on the task to be completed isn't meaningful please look check it out and make it more descriptive.
=> Check `How should this be manually tested?` part of the PR. 
> 3. We don't test the view, we test the action
=> Also Check `How should this be manually tested?` part of the PR.

2019-03-21 20:22 UTC, frankhn approved these changes

2019-03-22 08:03 UTC, cyrielo commented on config/index.js
> +  secret: process.env.NODE_ENV === 'production' ? process.env.SECRET : 'secret'
You should also have a local .env file for development

2019-03-22 08:04 UTC, cyrielo commented on index.js
> +    secret: 'authorshaven',
move this to the environment variable

2019-03-22 08:11 UTC, cyrielo requested changes
LGTM, see comments
PS: you should have a `.env` file to store your environment variables. Also, try to create a .env.sample file that would contain example values for those variables. only the ` .env.sample ` file should be committed and not the main .env file.

2019-03-22 10:38 UTC, cyrielo commented on .env
> +secretkey = "NewNewThings"
Remove this file from the commit and ignore the file using the `.gitignore` file. This file should be present in your folder but it should not be committed.

2019-03-22 10:39 UTC, cyrielo commented on .gitignore
> +.env
Great, I see you're ignoring it here

2019-03-22 10:45 UTC, cyrielo commented on config/index.js
> +  secret: process.env.NODE_ENV === 'production' ? process.env.SECRET : 'secret'
`secret: process.env.SECRET` should be enough

2019-03-25 09:56 UTC, cyrielo commented on config/index.js
> +  secret: process.env.NODE_ENV === 'production' ? process.env.SECRET : 'secret'
```
secret: (process.env.NODE_ENV === 'production') ?  process:  process.env.DEVELOPMENT_KEY
```
OR

```
module.exports = {
  develop: {
      secret: process.env.DEVELOP_SECRET
   },
  production: {
    secret: process.env.PRODUCTION_SECRET
  }
}
```

2019-03-25 10:00 UTC, merged