#164489776 installing mocha, chai, chai-http
andela/strikers-ah-backend pull request #2
Opened 2019-03-20 08:15 UTC by mystere10

**What does this PR do?**
This PR setup unit testing

**Description of Task to be completed?**
In order to test our endpoints, we need to setup unit testing which includes installing the following:
1. Mocha
2. Chai
3. Chai-http

**How should this be manually tested?**
This can be tested by cloning the repo then run `npm install` to install all dependencies, 
Then to run your test use `npm test`  

**What are the relevant pivotal tracker stories?**
#164489776 

**Screenshots**
![image](https://user-images.githubusercontent.com/34137067/54669038-07d19a80-4af9-11e9-8e3b-ec7759c09271.png)

2019-03-20 08:21 UTC, mwibutsa approved these changes

2019-03-20 08:37 UTC, frankhn requested changes
I really liked your work @mystere10,  but I would like to remind you that it's a better practice to make a difference between dev-dependencies and production dependencies. So that means since we use mocha, chai, and chai-HTTP in development,
 there shouldn't be in dependencies. better put them in dev-dependencies regards.

Help links: https://stackoverflow.com/questions/46903002/move-a-module-from-devdependencies-to-dependencies-in-npm-package-json
ref: https://dev.to/bnorbertjs/my-nodejs-setup-mocha--chai-babel7-es6-43ei

2019-03-20 10:33 UTC, frankhn approved these changes

2019-03-21 06:18 UTC, mwibutsa approved these changes

2019-03-22 08:38 UTC, cyrielo approved these changes
LGTM

2019-03-22 08:39 UTC, merged